version: '3.3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    command: "yarn run watch"
    volumes:
      - .:/app
    depends_on:
      - app

  db:
    image: mysql:8.0.32
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: news_aggregator_new
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./storage/dbdata:/var/lib/mysql
